"""Create AI assessment summary table

Revision ID: ai_assessment_summary_001
Revises: 
Create Date: 2025-07-15 09:55:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ai_assessment_summary_001'
down_revision = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_assessment_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_value', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date_value', name='_user_date_summary_uc')
    )
    op.create_index(op.f('ix_ai_assessment_summaries_id'), 'ai_assessment_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_assessment_summaries_id'), table_name='ai_assessment_summaries')
    op.drop_table('ai_assessment_summaries')
    # ### end Alembic commands ###