"""Create daily_activity_summary table

Revision ID: daily_activity_summary_001
Revises: 
Create Date: 2025-07-15 01:17:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'daily_activity_summary_001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_activity_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_value', sa.Date(), nullable=False),
    sa.Column('datatype', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('total_value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date_value', 'datatype', name='_user_date_datatype_uc')
    )
    op.create_index(op.f('ix_daily_activity_summary_id'), 'daily_activity_summary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_activity_summary_id'), table_name='daily_activity_summary')
    op.drop_table('daily_activity_summary')
    # ### end Alembic commands ###